# Generated by Django 3.2.4 on 2021-07-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
