# Generated by Django 3.2.4 on 2021-07-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Packed'), ('3', 'on the way'), ('4', 'Delivered'), ('5', 'Cancelled')], max_length=1),
        ),
    ]
